package gamesStore;

// Generated 2015-07-09 17:06:44 by Hibernate Tools 3.4.0.CR1

/**
 * Gamer generated by hbm2java
 */
public class Gamer implements java.io.Serializable
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 1L;

	private Integer				idGamer;
	private String				name;
	private String				lastName;

	public Gamer()
	{
	}

	public Gamer(String name, String lastName)
	{
		this.name = name;
		this.lastName = lastName;
	}

	public Integer getIdGamer()
	{
		return this.idGamer;
	}

	public void setIdGamer(Integer idGamer)
	{
		this.idGamer = idGamer;
	}

	public String getName()
	{
		return this.name;
	}

	public void setName(String name)
	{
		this.name = name;
	}

	public String getLastName()
	{
		return this.lastName;
	}

	public void setLastName(String lastName)
	{
		this.lastName = lastName;
	}

	public String toString()
	{
		return idGamer + "  " + lastName + "  " + name;
	}

}
